version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: postgres.dockerfile
    env_file: .env
    environment:
      - POSTGRESQL_ROOT_PASSWORD=${POSTGRESQL_ROOT_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_NAME}
      - POSTGRESQL_USER=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_TCP_PORT=${POSTGRESDB_LOCAL_PORT}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/data/postgres-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/
    ports:
      - ${POSTGRESDB_DOCKER_PORT}:${POSTGRESDB_LOCAL_PORT}

  api:
    container_name: api
    image: spring-boot-api
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${SPRING_DOCKER_PORT}:${SPRING_LOCAL_PORT}

    depends_on:
      - postgres
    environment:
      "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.PostgreSQLDialect"
      "spring.datasource.url": "jdbc:postgresql://postgres:5432/${DB_NAME}"
      "spring.datasource.username": ${DB_USER}
      "spring.datasource.password": ${DB_PASSWORD}
      "spring.jpa.hibernate.ddl-auto": "validate"
      "spring.liquibase.change-log": "classpath:db.changelog/db.changelog-master.yaml"
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - ${ANGULAR_LOCAL_PORT}:${ANGULAR_DOCKER_PORT}
    depends_on:
      - api
    volumes:
      - ./frontend:/src/app:delegated
      - /src/app/node_modules
      - /src/app/.angular

volumes:
  postgres_data: